import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { runMain } from './lib/cli.mjs';
import { loadConfig } from './lib/config.mjs';
import { normalizePath } from './lib/glob.mjs';
import { resolveRoot } from './lib/root.mjs';
import { loadWiki, wikiDir } from './lib/wiki.mjs';

const HEADER = '<!-- Generated by ship-faster. Do not edit: run /ship-faster:sync-docs to regenerate. -->\n# Wiki index\n';

const cell = (v) => String(v ?? '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim();

function table(label, rows) {
  if (!rows.length) return '';
  const out = [`| ${label} | Read when | Summary |`, '|---|---|---|'];
  for (const r of rows) out.push(`| [${cell(r.title)}](${r.link}) | ${cell(r.readWhen)} | ${cell(r.summary)} |`);
  return out.join('\n') + '\n';
}

export function buildIndex(root, config) {
  config = config || loadConfig(root).config;
  const wiki = loadWiki(root, config);
  const prefix = config.wikiDir.replace(/\/+$/, '') + '/';
  const rows = wiki.pages.map((p) => {
    const link = p.rel.startsWith(prefix) ? p.rel.slice(prefix.length) : p.rel;
    const d = p.data || {};
    return {
      link,
      title: d.title || link.split('/').pop().replace(/\.md$/, ''),
      readWhen: p.data ? d.read_when || '' : '(no frontmatter)',
      summary: p.data ? d.summary || '' : '',
      group: link.startsWith('recipes/') ? 'recipes' : link.startsWith('packages/') ? 'packages' : 'main',
    };
  }).sort((a, b) => (a.link < b.link ? -1 : a.link > b.link ? 1 : 0));
  let content = HEADER + '\n' + table('Page', rows.filter((r) => r.group === 'main'));
  const recipes = table('Recipe', rows.filter((r) => r.group === 'recipes'));
  if (recipes) content += '\n## Recipes\n\n' + recipes;
  const packages = table('Package', rows.filter((r) => r.group === 'packages'));
  if (packages) content += '\n## Packages\n\n' + packages;
  const path = join(wikiDir(root, config), 'index.md');
  const current = existsSync(path) ? readFileSync(path, 'utf8').replace(/\r\n/g, '\n') : null;
  return { ok: true, path: normalizePath(path), content, current, changed: current !== content, pages: rows.length };
}

export function writeIndex(root, config) {
  const r = buildIndex(root, config);
  if (r.changed) writeFileSync(r.path, r.content);
  return { ...r, written: r.changed, summary: [r.changed ? `index.md written (${r.pages} pages)` : `index.md up to date (${r.pages} pages)`] };
}

if (process.argv[1] && normalizePath(process.argv[1]).endsWith('/scripts/index.mjs')) {
  runMain((_, flags) => {
    const root = resolveRoot(flags);
    const { config } = loadConfig(root);
    if (flags.check) {
      const r = buildIndex(root, config);
      return r.changed ? { ...r, ok: false, error: 'index.md is out of date', content: undefined } : { ...r, content: undefined, summary: ['index.md up to date'] };
    }
    const r = writeIndex(root, config);
    return { ...r, content: undefined, current: undefined };
  });
}
