import { test, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpDir, runScript, cleanupAll } from './helpers.mjs';
import { serializeFrontmatter } from '../scripts/lib/fm.mjs';
import { DEFAULTS } from '../scripts/lib/config.mjs';
import { buildIndex, writeIndex } from '../scripts/index.mjs';

after(cleanupAll);
beforeEach(() => { process.env.CLAUDE_PLUGIN_DATA = tmpDir('sf-data-'); });

const page = (title, summary, read_when) => serializeFrontmatter({ title, summary, read_when, covers: ['x'], verified: 'abc', updated: '2026-09-16' }) + '# x\n';

function wiki() {
  const root = tmpDir();
  const w = join(root, 'docs', 'wiki');
  mkdirSync(join(w, 'recipes'), { recursive: true });
  mkdirSync(join(w, 'packages'), { recursive: true });
  writeFileSync(join(w, 'commands.md'), page('Commands', 'Verified | commands.', 'You need to run anything.'));
  writeFileSync(join(w, 'architecture.md'), page('Architecture', 'Components.', 'Changing structure.'));
  writeFileSync(join(w, 'recipes', 'add-endpoint.md'), page('Add an endpoint', 'Steps.', 'Adding an API route.'));
  writeFileSync(join(w, 'nofm.md'), '# plain\n');
  return { root, w };
}

test('builds grouped, sorted, escaped tables and is byte-stable', () => {
  const { root, w } = wiki();
  const a = buildIndex(root, DEFAULTS);
  assert.equal(a.changed, true);
  assert.equal(a.current, null);
  assert.match(a.content, /^<!-- Generated by ship-faster\./);
  const lines = a.content.split('\n');
  const main = lines.filter((l) => l.startsWith('| ['));
  assert.deepEqual(main.map((l) => l.slice(0, l.indexOf(']'))), ['| [Architecture', '| [Commands', '| [nofm', '| [Add an endpoint']);
  assert.ok(a.content.includes('| [Commands](commands.md) | You need to run anything. | Verified \\| commands. |'));
  assert.ok(a.content.includes('| [nofm](nofm.md) | (no frontmatter) |  |'));
  assert.ok(a.content.includes('## Recipes'));
  assert.ok(!a.content.includes('## Packages'));
  assert.ok(!a.content.includes('\n\n\n'));
  const w1 = writeIndex(root, DEFAULTS);
  assert.equal(w1.written, true);
  assert.equal(readFileSync(join(w, 'index.md'), 'utf8'), a.content);
  const w2 = writeIndex(root, DEFAULTS);
  assert.equal(w2.written, false);
  assert.equal(w2.changed, false);
});

test('--check reports an out-of-date index without writing', () => {
  const { root, w } = wiki();
  writeIndex(root, DEFAULTS);
  writeFileSync(join(w, 'commands.md'), page('Commands', 'New summary.', 'You need to run anything.'));
  const cli = runScript('index', ['--root', root, '--check', '--json']);
  assert.equal(cli.json.ok, false);
  assert.match(cli.json.error, /out of date/);
  assert.ok(!readFileSync(join(w, 'index.md'), 'utf8').includes('New summary.'));
  const fix = runScript('index', ['--root', root, '--json']);
  assert.equal(fix.json.written, true);
  assert.equal(runScript('index', ['--root', root, '--check', '--json']).json.ok, true);
});

test('creates wiki directory and writes index on fresh repository', () => {
  const root = tmpDir();
  const indexPath = join(root, 'docs', 'wiki', 'index.md');
  const w1 = writeIndex(root, DEFAULTS);
  assert.equal(w1.written, true);
  assert.equal(w1.pages, 0);
  assert.ok(readFileSync(indexPath, 'utf8').length > 0);
  assert.ok(!readFileSync(indexPath, 'utf8').includes('\n\n\n'));
  const w2 = writeIndex(root, DEFAULTS);
  assert.equal(w2.written, false);
});
